model:
  name: medium
  language: en
  min_speaker: 2
  max_speaker: 2
  batch_size: 16
  temperatures: 0.3
  initial_promp: null
  compute_type: float32

subtitles:
  max_char: 42

output:
  folder: null